package simple.repo.arch;

import lombok.Builder;
import lombok.Data;
import lombok.SneakyThrows;
import lombok.experimental.Accessors;
import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream;
import org.apache.commons.compress.compressors.zstandard.ZstdCompressorOutputStream;
import org.springframework.util.StringUtils;
import simple.repo.Version;
import simple.repo.model.*;
import simple.repo.packaging.FileSpecReader;
import simple.repo.packaging.PackageBuilder;

import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.util.*;
import java.util.stream.IntStream;
import java.util.zip.GZIPOutputStream;

@Data
@Accessors(chain = true)
public class ArchPackageBuilder implements PackageBuilder {
    ArchCompression compression = ArchCompression.zst;
    FileSpecReader fileSpecReader = new FileSpecReader();

    @Override
    public String outputType() {
        return RepoOutputArch.OUTPUT_NAME;
    }

    /**
     * @see <a href=https://rfc.archlinux.page/0032-arch-linux-ports/>rfc.archlinux.page: arch's arch list</a>
     */
    @Override
    public String archName(Arch arch) {
        return switch (arch) {
            case amd64 -> "x86_64";
            case arm64 -> "aarch64";
            // https://man.archlinux.org/man/PKGBUILD.5#OPTIONS_AND_DIRECTIVES
            // Packages that contain no architecture specific files should use arch=('any')
            case null -> "any";
            default -> throw new UnsupportedOperationException("arch only officially supports amd64");
        };
    }

    @Override
    public String fileName(PackageConfig packageConfig) {
        PackageConfig.PackageMeta meta = packageConfig.getMeta();
        var stringBuilder = new StringBuilder(meta.getName());
        stringBuilder.append('-').append(meta.getVersion());

        if (StringUtils.hasText(meta.getReleaseVersion()))
            stringBuilder.append('-').append(meta.getReleaseVersion());

        stringBuilder.append('-').append(archName(meta.getArch()));
        stringBuilder.append(".pkg.tar.").append(compression.name());
        return stringBuilder.toString();
    }

    @Override
    public PackageConfig.PackageMeta metaFromFileName(String fileName) {
        throw new UnsupportedOperationException();
    }

    private String getPackageVersion(PackageConfig.PackageMeta m) {
        var relPart = m.getReleaseVersion() == null ? "" : "-" + m.getReleaseVersion();
        return m.getVersion() + relPart;
    }

    /**
     * An Arch package is no more than a tar(1) archive, or a tarball,
     * compressed using zstd(1), which contains the following files generated by makepkg:
     * <p>
     * The binary files to install.
     * .PKGINFO — contains all the metadata needed by pacman to deal with packages, dependencies, etc.
     * .BUILDINFO — contains information needed for reproducible builds, also see BUILDINFO(5) and BUILDINFOv2(5).
     * .MTREE — contains hashes and timestamps of the files, which are included in the local database so that pacman can verify the integrity of the package.
     * .INSTALL — an optional file used to execute commands after the install/upgrade/remove stage (this file is present only if specified in the PKGBUILD).
     * .Changelog — an optional file kept by the package maintainer documenting the changes of the package.
     */
    @SneakyThrows
    @Override
    public FileIntegrityWithContent buildPackage(PackageConfig packageConfig) {
        var dataFileSpecs = packageConfig.getFiles().getDataFiles();
        // read
        var dataFiles = fileSpecReader.readContents(dataFileSpecs);
        // combine with specs
        var dataFileSpecsWithContents = IntStream.range(0, dataFileSpecs.size())
                .mapToObj(i -> new FileSpecWithContent(dataFileSpecs.get(i), dataFiles.get(i)))
                .toList();

        var buildInfoData = toBuildInfoData(packageConfig);
        var buildInfo = render(buildInfoData);
        var buildInfoBytes = buildInfo.getBytes();

        var pkgInfoData = toPkgInfoData(packageConfig, dataFileSpecsWithContents);
        var pkgInfo = render(pkgInfoData);
        var pkgInfoBytes = pkgInfo.getBytes();

        var mtreeData = toMTreeData(dataFileSpecsWithContents);
        var mtree = render(mtreeData);
        var mtreeGZipped = gzip(mtree);

        // noinspection OctalInteger
        var extraInnerFiles = List.of(
                new FileSpecWithContent(FileIntegrityWithContent.of(buildInfoBytes, ".BUILDINFO"), 0644),
                new FileSpecWithContent(FileIntegrityWithContent.of(mtreeGZipped, ".MTREE"), 0644),
                new FileSpecWithContent(FileIntegrityWithContent.of(pkgInfoBytes, ".PKGINFO"), 0644)
        );
        var outerFiles = new ArrayList<FileSpecWithContent>(dataFiles.size() + 3);
        outerFiles.addAll(extraInnerFiles);
        outerFiles.addAll(dataFileSpecsWithContents);
        var content = createTarZst(outerFiles);

        return new FileIntegrityWithContent()
                .setContent(content)
                .setFileIntegrity(FileIntegrity.of(content, fileName(packageConfig)));
    }

    @Override
    public PackageConfig parseConfigFromPackage(byte[] downloadedPackage) {
        throw new UnsupportedOperationException();
    }

    //<editor-fold desc="to data">
    private ArchPkgFilesData.BuildInfoData toBuildInfoData(PackageConfig packageConfig) {
        return ArchPkgFilesData.BuildInfoData.builder()
                .format(2)
                .pkgname(packageConfig.getMeta().getName())
                .pkgbase(packageConfig.getMeta().getName())
                .pkgver(getPackageVersion(packageConfig.getMeta()))
                .pkgarch(archName(packageConfig.getMeta().getArch()))
                // we dont actually have one lol wtf
                .pkgbuild_sha256sum(null)
                .packager(packageConfig.getMeta().getReleaser())
                .builddate(Instant.now())
                // builddir = /build
                // startdir = /startdir
                .builddir("/build")
                .startdir("/startdir")
                .buildtool("simple-package-repo-4j")
                // todo fixme
                .buildtoolver(Version.VERSION)
                .buildenv(ArchPkgFilesData.BuildInfoData.BUILD_ENV_DEFAULTS)
                .options(ArchPkgFilesData.BuildInfoData.OPTIONS_DEFAULTS)
                .installed(List.of())
                .build();
    }

    private ArchPkgFilesData.PkgInfoFields toPkgInfoData(PackageConfig packageConfig, List<FileSpecWithContent> dataFileSpecsWithContents) {
        var meta = packageConfig.getMeta();
        var control = packageConfig.getControl();

        return ArchPkgFilesData.PkgInfoFields.builder()
                .generatedBy("simple-repo")
                .pkgname(meta.getName())
                .pkgbase(meta.getName())
                .xdataPkgType(ArchPkgFilesData.PkgInfoFields.PkgType.pkg)
                .xdata(Map.of())
                .pkgver(getPackageVersion(meta))
                .pkgdesc(control.getDescription())
                .url(control.getHomepage())
                .builddate(Instant.now())
                .packager(control.getMaintainer())
                .size(dataFileSpecsWithContents.stream()
                        .map(FileSpecWithContent::content)
                        .map(FileIntegrityWithContent::getContent)
                        .mapToInt(f -> f.length)
                        .sum())
                .arch(archName(meta.getArch()))
                .license("unknown")
                .depend(Arrays.asList(control.getDepends().split(",\\s{0,10}")))
                .build();
    }

    private ArchPkgFilesData.MTreeData toMTreeData(
            List<FileSpecWithContent> fileSpecWithContentList
    ) {
        List<ArchPkgFilesData.MTreeData.MTreeLine> lines = new ArrayList<>();

        var fileLines = fileSpecWithContentList.stream()
                .map(fileSpecWithContent -> {
                    var path = fileSpecWithContent.path();
                    var mode = fileSpecWithContent.mode();
                    var content = fileSpecWithContent.content().getContent();
                    return new ArchPkgFilesData.MTreeData.MTreeLine.FileLine(path, null, mode, ArchPkgFilesData.MTreeData.MTreeLine.Type.file, content.length, fileSpecWithContent.content().getFileIntegrity());
                })
                .toList();

        // first 2 get file/644
        // noinspection OctalInteger
        lines.add(new ArchPkgFilesData.MTreeData.MTreeLine.SetLine(ArchPkgFilesData.MTreeData.MTreeLine.Type.file, 0, 0, 0_644));

        // first 2 just go first
        lines.addAll(fileLines.subList(0, 2));

        // get all directories? make them with 644

        return new ArchPkgFilesData.MTreeData(lines);
    }
    //</editor-fold>

    //<editor-fold desc="rendering data">
    private String render(ArchPkgFilesData.BuildInfoData buildInfoData) {
        throw new UnsupportedOperationException();
    }

    private String render(ArchPkgFilesData.PkgInfoFields pkgInfoFields) {
        var sb = new StringBuilder();
        if (Objects.nonNull(pkgInfoFields.generatedBy))
            sb.append("# Generated by ").append(pkgInfoFields.generatedBy).append("\n");
        sb.append("pkgname = ").append(pkgInfoFields.pkgname).append("\n");
        sb.append("pkgbase = ").append(pkgInfoFields.pkgbase).append("\n");

        // xdata
        sb.append("xdata = pkgtype=").append(pkgInfoFields.xdataPkgType.name());
        if (Objects.nonNull(pkgInfoFields.xdata)) {
            for (var s : pkgInfoFields.xdata.entrySet()) {
                sb.append(",").append(s.getKey()).append("=").append(s.getValue());
            }
        }
        sb.append("\n");

        sb.append("pkgver = ").append(pkgInfoFields.pkgver).append("\n");
        sb.append("pkgdesc = ").append(pkgInfoFields.pkgdesc).append("\n");
        sb.append("url = ").append(pkgInfoFields.url).append("\n");
        sb.append("builddate = ").append(pkgInfoFields.builddate.getEpochSecond()).append("\n");
        sb.append("packager = ").append(pkgInfoFields.packager).append("\n");
        sb.append("size = ").append(pkgInfoFields.size).append("\n");
        sb.append("arch = ").append(pkgInfoFields.arch).append("\n");
        sb.append("license = ").append(pkgInfoFields.license).append("\n");
        if (Objects.nonNull(pkgInfoFields.depend)) {
            for (var s : pkgInfoFields.depend) {
                sb.append("depend = ").append(s).append("\n");
            }
        }

        return sb.toString();
    }

    @SuppressWarnings("OctalInteger")
    private String render(ArchPkgFilesData.MTreeData mTreeData) {
        var sb = new StringBuilder("#mtree");
        for (var line : mTreeData.lines) {
            switch (line) {
                case ArchPkgFilesData.MTreeData.MTreeLine.SetLine setLine -> {
                    sb.append("/set");
                    if (setLine.type != null) sb.append(" type=").append(setLine.type);
                    if (setLine.uid != null) sb.append(" uid=").append(setLine.uid);
                    if (setLine.gid != null) sb.append(" gid=").append(setLine.gid);
                    if (setLine.mode != null)
                        sb.append(" mode=").append(Integer.toString(setLine.mode & 0777, 8)); // only print rwx part
                }
                case ArchPkgFilesData.MTreeData.MTreeLine.FileLine fileLine -> {
                    sb.append(".").append(fileLine.name);
                    if (fileLine.time != null) sb.append(" time=").append(fileLine.time.getEpochSecond()).append(".0");
                    if (fileLine.mode != null)
                        sb.append(" mode=").append(Integer.toString(fileLine.mode & 0777, 8)); // only print rwx part
                    if (fileLine.type != null) sb.append(" type=").append(fileLine.type);
                    if (fileLine.size != null) sb.append(" size=").append(fileLine.size);
                    if (fileLine.hashes != null && fileLine.hashes.getSha256() != null)
                        sb.append(" sha256digest=").append(fileLine.hashes.getSha256());
                }
            }
            sb.append("\n");
        }
        return sb.toString();
    }
    //</editor-fold>

    //<editor-fold desc="compression">
    @SneakyThrows
    private byte[] gzip(String raw) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (GZIPOutputStream gzip = new GZIPOutputStream(out)) {
            gzip.write(raw.getBytes());
        }
        return out.toByteArray();
    }

    @SneakyThrows
    private byte[] createTarZst(List<FileSpecWithContent> allFiles) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (TarArchiveOutputStream tarOut = new TarArchiveOutputStream(new ZstdCompressorOutputStream(out))) {
            // tarOut.setLongFileMode(TarArchiveOutputStream.LONGFILE_GNU);

            for (FileSpecWithContent f : allFiles) {

                byte[] content = f.content().getContent();
                TarArchiveEntry entry = new TarArchiveEntry(f.path());
                entry.setSize(content.length);

                if (f.mode() != null) {
                    entry.setMode(f.mode());
                }

                tarOut.putArchiveEntry(entry);
                tarOut.write(content);
                tarOut.closeArchiveEntry();
            }
        }
        return out.toByteArray();
    }
    //</editor-fold>

    record ArchPkgFilesData() {
        /**
         * @param format             Denotes the file format version, represented by a plain positive integer.
         * @param pkgname            The name of the package.
         * @param pkgbase            The base name of a package, usually the same as the pkgname except for split packages.
         * @param pkgver             The version of the package including pkgrel and epoch.
         * @param pkgarch            The architecture of the package.
         * @param pkgbuild_sha256sum The sha256sum in hex format of the PKGBUILD used to build the package.
         * @param packager           The details of the packager that built the package.
         * @param builddate          The build date of the package in epoch.
         * @param builddir           The directory where the package was built.
         * @param startdir           The directory from which makepkg was executed.
         * @param buildtool          The name of the tool ecosystem used to set up the build environment.
         *                           Used for defining a spec for reproducible builds, e.g. the source of the makepkg.conf(5) used.
         * @param buildtoolver       The full version of the buildtool, for example: "$pkgver-$pkgrel-$pkgarch".
         * @param buildenv           (array) The build environment specified in makepkg.conf.
         * @param options            (array) The options set specified when building the package.
         * @param installed          (array) The installed packages at build time including the version information of the package. Formatted as "$pkgname-$pkgver-$pkgrel-$pkgarch".
         * @see <a href=https://man.archlinux.org/man/BUILDINFO.5>man.archlinux.org: man BUILDINFO</a>
         */
        @Builder
        record BuildInfoData(
                int format,
                String pkgname,
                String pkgbase,
                String pkgver,
                String pkgarch,
                String pkgbuild_sha256sum,
                String packager,
                Instant builddate,
                String builddir,
                String startdir,
                String buildtool,
                String buildtoolver,
                List<String> buildenv,
                List<String> options,
                List<String> installed
        ) {
            /**
             * This array contains options that affect the build environment; the defaults are shown here.
             *
             * @see <a href=https://man.archlinux.org/man/makepkg.conf.5.en>man.archlinux.org: man makepkg</a>
             */
            static final List<String> BUILD_ENV_DEFAULTS = List.of("!distcc", "!color", "!ccache", "check", "!sign");

            /**
             * This array contains options that affect default packaging.
             * They are equivalent to options that can be placed in the PKGBUILD;
             * the defaults are shown here.
             *
             * @see <a href=https://man.archlinux.org/man/makepkg.conf.5.en>man.archlinux.org: man makepkg</a>
             */
            static final List<String> OPTIONS_DEFAULTS = List.of("!strip", "docs", "libtool", "staticlibs", "emptydirs");
        }

        @Builder
        record PkgInfoFields(
                String generatedBy,
                String pkgname,
                String pkgbase,
                PkgType xdataPkgType,
                Map<String, String> xdata, // pkgtype=split
                String pkgver, // = 0.33-3
                String pkgdesc, // = Useful set of utilities for interacting with a cloud (cloud images)
                String url, // = https://github.com/canonical/cloud-utils
                Instant builddate, // = 1752758345
                String packager, // = Arch Linux ARM Build System <builder+n1@archlinuxarm.org>
                Integer size, // = 40360
                String arch, // = any
                String license, // = GPL-3.0-only
                List<String> depend // = bash
        ) {
            /**
             * A PKGINFO must contain an xdata keyword assignment
             * that defines a pkgtype assignment in its value (e.g. pkgtype=pkg).
             * <p>
             * The valid pkgtype values are
             * debug (for debug packages),
             * pkg (for single packages),
             * src (for source packages) and
             * split (for split packages).
             *
             * @see <a href=https://man.archlinux.org/man/PKGINFO.5.en>man.archlinux.org: man PKGINFO</a>
             */
            enum PkgType {
                debug, pkg, src, split
            }
        }

        record MTreeData(List<MTreeLine> lines) {
            sealed interface MTreeLine {
                // https://man.archlinux.org/man/ALPM-MTREE.5.en
                // In contrast to all available types in mtree, ALPM-MTREE only allows three file types:
                enum Type { dir, file, link }

                record SetLine(Type type, Integer uid, Integer gid, Integer mode) implements MTreeLine {
                }

                record FileLine(String name, Instant time, Integer mode, Type type, Integer size,
                                FileIntegrity hashes) implements MTreeLine {
                }
            }
        }
    }

    public enum ArchCompression {
        // gz?
        xz, zst,
    }
}
