on:
  pull_request:
    branches: &branches
      - main
    paths: &paths
      - .github/workflows/build.yaml
      - '**/*.java'
      - '**/*.gradle'
    types:
      - opened
      - synchronize
  push:
    branches: *branches
    paths: *paths

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v6
      - run: |
          ./gradlew build
